package com.iomete.cleanup.untrackedtablefolders.audit

import java.time.Instant

data class CleanupAuditRecord(
    val runId: String,
    val sparkAppId: String?,
    val initiatedBy: String?,
    val runtimeComputeId: String?,
    val runtimeComputeNamespace: String?,
    val runtimeDomain: String?,
    val runtimeUser: String?,
    val catalogName: String,
    val databaseName: String,
    val operation: String,
    val dryRun: Boolean,
    val deleteEnabled: Boolean,
    val olderThanHours: Long,
    val cutoffTime: Instant?,
    val maxCandidateFoldersPerDatabase: Int,
    val excludedPaths: List<String>,
    val status: String,
    val statusReason: String?,
    val errorMessage: String?,
    val discoveredDatabaseLocation: String?,
    val storageScanLocation: String,
    val activeTableCount: Long,
    val storageFolderCount: Long,
    val candidateFolderCount: Long,
    val candidateObjectCount: Long,
    val candidateTotalSizeBytes: Long,
    val deletedFolderCount: Long,
    val deletedObjectCount: Long,
    val deletedTotalSizeBytes: Long,
    val candidateFolders: List<String>,
    val deletedFolders: List<String>,
    val diagnosticDetails: Map<String, String>,
    val startTime: Instant,
    val endTime: Instant,
)
