application:
  exclude-schemas: []
  catalog-endpoint: "http://iom-catalog"

"presidio/mp-rest/url": http://presidio-analyzer
"core-service/mp-rest/url": http://iom-core/api/internal/spark-settings

quarkus:
  package:
    type: uber-jar
  http:
    port: 0
  banner:
    enabled: false
  log:
    level: INFO
    category:
      com.iomete:
        level: INFO
    console:
      json: false

"%dev":
  quarkus:
    log:
      category:
        com:
          level: INFO
      console:
        json: false
